### PR TITLE
[FEATURE]navigation list item hover and focus effect

### PR DESCRIPTION
**Pull request by Islam888**
Hover, focus effect for the navigation items by using `before` pseudo-element, and utilizing `transform: scale()` property.

### CODE REVIEW

**Comment by Islam888** [comment]
Hello!
I made this pull request 8 days ago. I just would like to receive any comment regarding it. Is there any problem with it?  or any other comment?

**Comment by Chalarangelo** [comment]
@Islam888 Sorry, we haven't had time to review just yet. I hope I can find some time to take a look later today. Thanks for bumping this up, things can end up in the ToDo list for a while sometimes! :stuck_out_tongue_winking_eye:

**Comment by Islam888** [comment]
> Thanks for contributing!
> 
> Seems like there is a lot of flashing when I test this in a Codepen on Chrome. Seems like the background is flashing over time when you move from one element to the next. This is not great for the implementation, please fix this.

Hello!
Thank you for your feedback. I just tested the code again and found no background flashing as said. I just need more explanation what flashing you meant. A notice is that the effect the code produce is just a background color that fill the background of each nav item while hovering or focusing it.
Thank you!

**Comment by Islam888** [comment]
I recorded the screen to clarify my point here https://drive.google.com/open?id=12E720Yu1DGjefJnkLxPU1ox3pz9KYGGg

Thank you!

**Comment by atomiks** [comment]
Works fine for me without flashing

**Comment by Chalarangelo** [comment]
Seems like it was an issue with my laptop rendering it. Can we hold off and merge it tomorrow so I can test on a similar setup with better specs just in case? Mighr be interesting to know why this happens.

**Comment by Islam888** [comment]
Thank you

**Pull request merged**
