### PR TITLE
[FEATURE] Add multiline truncate text

### LINKED ISSUE #133: [FEATURE] Multiline truncation
What about multiline truncation with `line-clamp`? I can make usage example.
https://caniuse.com/#search=line-clamp

### PR DESCRIPTION
**Pull request by teleginzhenya**
Multiline truncate text
Resolves #133

### CODE REVIEW

**Comment by Chalarangelo** [comment]
I tested it recently on Firefox and it did not work properly, but I'll recheck. Maybe I've missed something?

**Comment by teleginzhenya** [comment]
image
You're right, it doesn't add `...` in Firefox, but still truncates to `n` lines

**Comment by teleginzhenya** [comment]
As far as I know, not yet :(

**Comment by atomiks** [comment]
How about gradient fade truncation? The one Wikipedia uses for its popover things

**Comment by Chalarangelo** [comment]
@atomiks I like that opytion a lot, too!

**Comment by teleginzhenya** [comment]
@Chalarangelo don't you think that it should be another snippet? If I add gradient fade truncation, there won't be `...`

**Comment by Chalarangelo** [comment]
I prefer the gradient fade version for now as it is supported by more browsers and seems slightly more impressive presentation-wise. The WebKit specific rules could be added as another snippet later down the line when support is better across-the-board.

**Comment by teleginzhenya** [comment]
Alright, will make commits soon in this PR (:

**Pull request merged**
