### PR TITLE
A new transition effect ( hover-shadow-box).

### PR DESCRIPTION
**Pull request by sachans**
Adding one hovering effect

### CODE REVIEW

**Comment by sachans** [comment]
Is anyone there?

**Comment by sachans** [comment]
@atomiks I have created solutions of all the issues which you gave but i'm not able to resolve the chrome glitch effect.
Can you help me to find what that error is?

**Comment by atomiks** [comment]
I think it's a recent Chrome/Blink bug tbh, I never had problems with scaling 1px glitches until the last two or so Chrome versions...

**Comment by sachans** [comment]
So, Would you merge it or not?

**Comment by atomiks** [comment]
There are a few changes I need to make to this still, but I should merge after I'm finished

**Comment by sachans** [comment]
OK thanks though.
This was my First Pull request

**Comment by equinusocio** [comment]
There is the `h4` reference inside the explanation

**Comment by sachans** [comment]
@atomiks  did you done your changes in it?

**Pull request merged**
