### PR TITLE
Autoscoping 

### PR DESCRIPTION
**Pull request by atomiks**
- Need to update all problematic snippets before merging
- Removed `grid-layout.md` because it broke the global styles -- I don't believe it's very useful anyway in this repo's format...

### CODE REVIEW

**Comment by skatcat31** [comment]
Nice clean code there @atomiks and since this is a build script, sync is a great choice to make sure you aren't overloading the memory available. I wonder if a map might be better with the sync read inside it though? I'm not certain it would bring any extra functionality or added ability... either way great modification.

**Comment by skatcat31** [comment]
however I did notice there is no installation of `node-sass` in the `package.json`

**Comment by atomiks** [comment]
@skatcat31 It's already there because of the website: https://github.com/30-seconds/30-seconds-of-css/blob/master/package.json#L26

Code is kinda hackish because it's just regex but it works 😜

**Comment by atomiks** [comment]
Need to do JavaScript as well...

**Comment by atomiks** [comment]
Everything's working fine. Next PR will be to use a line highlight to only highlight the relevant parts of the CSS like React's docs do. This is the ideal solution to the problem of including extraneous code (but necessary to reproduce the demo faithfully) while highlighting the actual properties required for the effect.

**Comment by skatcat31** [comment]
I like the IIFE. Nice idea to scope the variables and make sure there is overrun from global space. Great job!

**Pull request merged**
