### PR TITLE
Add a new snippet: CSS toggle switch

### PR DESCRIPTION
**Pull request by daihuaye**

### CODE REVIEW

**Comment by atomiks** [comment]
Another great snippet. Couple suggestions:

- Transition for the knob?
- More aesthetically pleasing color than `blue`?

Looks great other than that

**Comment by atomiks** [comment]
One thing I noticed, and it's extremely subtle, but the knob has tiny 1px jerks as it finishes the transition because it's translating `left` instead of `transform`. `transform` uses subpixels instead of whole pixels which looks better (especially on HiDPI displays) and is more performant to animate.

I think you can do this:

```css
input[type="checkbox"]:checked+.switch::after {
  left: 0;
  transform: translateX(21px);
  /* remove margin-left: -1px */
}
```

**Comment by daihuaye** [comment]
@atomiks Thanks! That's good suggestion. I agree that use transform will help animation and is more smooth than use left property. Also yeah, the your change for `.offscreen` will help accessibility. 

One thing is the `translateX(21px)` will make the knob touch the edge of `<label>` container, It will look good if there is 1px off, which is the same as start state, right?

**Comment by atomiks** [comment]
> One thing is the translateX(21px) will make the knob touch the edge of <label> container, It will look good if there is 1px off, which is the same as start state, right?

With `left: 0`, you need `21px`, but if we don't set `left` at all, we only need `20px` because of the original `left: 1px`.

I've made some improvements and I think it's ready now 👍

**Comment by daihuaye** [comment]
Looks good to me. Thanks!

**Comment by daihuaye** [comment]
@atomiks  Any more comment? Just wonder when will it merge to master branch if everything looks good?

**Pull request merged**
