### PR TITLE
add button-hover-fill-animation

### PR DESCRIPTION
**Pull request by hwilson2563**
Is this a new component ?
Yes

About the component
This is a button that has a fill animation on hover/action.

Code Pen
You can find a working codepen example in the following link
https://codepen.io/hwilson2563/pen/jOrEWLM

** is it possible to add this as a valid [Hacktoberfest Contribution](https://hacktoberfest.digitalocean.com/hacktoberfest-update) by assigning an official label 😃 ?

### CODE REVIEW

**Comment by crew-guy** [comment]
> ** is it possible to add this as a valid [Hacktoberfest Contribution](https://hacktoberfest.digitalocean.com/hacktoberfest-update) by assigning an official label 😃 ?

Was it valid for Hacktoberfest ? @hwilson2563

**Comment by hwilson2563** [comment]
@crew-guy I believe so, it is increasing documentation for your css lib as long as you are okay with the work I am adding.

**Comment by crew-guy** [comment]
> @crew-guy I believe so, it is increasing documentation for your css lib as long as you are okay with the work I am adding.

Gotcha ! Thanks !

**Comment by hwilson2563** [comment]
> > @crew-guy I believe so, it is increasing documentation for your css lib as long as you are okay with the work I am adding.
> 
> Gotcha ! Thanks !

If you wish to not add the whole repo you can add a label to just the pr:  hacktoberfest-accepted

**Review by Chalarangelo — APPROVED** [review]

**Pull request merged**
